name: dev_env

services:
  redis:
    image: redis
    ports:
     - 6379:6379
    volumes:
     - ./redis/data:/data

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: SHOW_ME_THE_DATA
    volumes:
      - ./mariadb/data:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - 80:80
    working_dir: /srv
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./projects/:/srv

  php83:
    build:
      context: ./php/83
    working_dir: /srv/php83
    volumes:
      - ./projects/php83:/srv/php83

  php74:
    build:
      context: ./php/74
    working_dir: /srv/php74
    volumes:
      - ./projects/php74:/srv/php74

