server {
    listen       80;
    listen  [::]:80;
    server_name  demo85.test;
    root   /srv/php85/demo;

    index  index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php85:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    access_log /dev/stdout;
    error_log /dev/stderr warn;
}

